spring:
  application:
    name: devolucion
  profiles:
    active: dev

server:
  port: 8095

ms:
  venta:
    url: http://localhost:8086
  cliente:
    url: http://localhost:8082
  empleado:
    url: http://localhost:8081
  tarjeta:
    url: http://localhost:8091
  producto:
    url: http://localhost:8083

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
