spring:
  application:
    name: oferta
  profiles:
    active: dev

server:
  port: 8092

ms:
  producto:
    url: http://localhost:8083

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
