spring:
  datasource:
    url: jdbc:mysql://localhost:3306/patata
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    default-schema: patata
    enabled: true
