spring:
  application:
    name: tienda
  profiles:
    active: dev

server:
  port: 8085

ms:
  empleado:
    url: http://localhost:8081

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
