spring:
  application:
    name: inventario
  profiles:
    active: dev

server:
  port: 8093

ms:
  producto:
    url: http://localhost:8083
  tienda:
    url: http://localhost:8085

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
