spring.application.name=ms-genero

# Puerto diferente al ms-persona (que usará 8080)
server.port=8081

# Base de datos propia del microservicio
spring.datasource.url=jdbc:mysql://localhost:3306/db_genero
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Basic Auth para este microservicio
spring.security.user.name=admin
spring.security.user.password=admin123

# Logs propios del microservicio
logging.file.name=logs/ms-genero.log
logging.level.root=INFO
logging.level.com.ejemplo.genero=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
